sim:
  fps: 30 # int
  render_realtime: True # boolean
  observation_space_format: classes # "rgb" or "classes"
car:
  wheelbase: 0.0487 # m
  track_width: 0.027 # m
  max_velocity: 0.1 # m/s
  max_steering_angle: 35 # deg
  steering_speed: 30 # deg/s
  max_acceleration: 0.1 # m/s^2
  max_deceleration: 1.0 # m/s^2
camera:
  position: [0.02,0,0.024] # [x,y,z] in m relative to middle of front axle (x: forward, y: right, z: up)
  orientation: [15,0,0] # [pitch,roll,yaw] in degrees
  resolution: [128,160] # [height, width] in px
  fov: 120 # in degrees
  max_range: 0.5 # in m (can be None for infinite range)
  line_thickness: 4 # in px
map:
  json_path: ./maps/simple_layout.json # path to map file
  pixel_per_meter: 450
